# Generated by Django 3.0.7 on 2020-08-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('acno', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('ftname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('adhar', models.IntegerField(unique=True)),
                ('national', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='images/')),
                ('sign', models.ImageField(upload_to='images/')),
                ('house', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('dist', models.CharField(max_length=50)),
            ],
        ),
    ]
